version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5-node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build website
          command: |
            bundle exec middleman build

      - run:
          name: Deploy website
          command: |
            bundle exec middleman s3_sync
